### ISSUE TITLE
How to Clean Reinstall?

### ISSUE THREAD

**Issue by enchant3dmango** [subframe7536/vscode-custom-ui-style#32]
Hi all, previously I had `custom-ui-style.stylesheet` as follows.
```css
"custom-ui-style.stylesheet": {
  ".monaco-editor-hover .monaco-hover": "box-shadow: 0px 8px 32px rgba(0,0,0,.45) !important; background-image: linear-gradient(#3c3c50 0%, #2a2b38 100%) !important; backdrop-filter: blur(3px) !important; border-radius: 16px !important;	border: none !important; outline: 0px !important;
  ...
}
```
With this result.

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/35d9c46c-ed1e-40e2-88e6-af3277ce721a" />

I have already deleted the style above from my `custom-ui-style.stylesheet` and restarted my VS Code. But the style (as in the above screenshot) is still there. I have already restarted it many times. I just want to revert it to default. Kindly help, thanks in advance!

**Comment by enchant3dmango** [comment]
This is the current full `custom-ui-style.stylesheet`.

```css
"custom-ui-style.stylesheet": {
    ".editor-widget.find-widget": "box-shadow: none; border-radius: 4px",
    ".monaco-action-bar.quick-input-inline-action-bar": "display: none",
    ".monaco-editor .cursors-layer .cursor": "background-image: linear-gradient(135deg, #FFC0CB 10%, #DA70D6 100%)",
    ".monaco-editor .scroll-decoration": "box-shadow: 0px 0px 20px rgba(0, 0, 0, .75) !important; top: -6px !important;",
    ".monaco-list-row.focused": "outline: none !important",
    ".monaco-workbench .monaco-list:not(.element-focused):focus:before": "outline: none !important",
    ".monaco-workbench .part.editor > .content .editor-group-container > .title > .label-container > .title-label": "padding-left: 60px",
    ".monaco-workbench .part.editor > .content .editor-group-container > .title.title-border-bottom:after": "display: none",
    ".monaco-scrollable-element > .shadow.top": "display: none",
    ".notification-toast": "box-shadow: none !important",
    ".quick-input-list .scrollbar": "display: none",
    ".quick-input-titlebar": "background: #100B15 !important",
    ".quick-input-widget": "top: 25vh !important",
    ".quick-input-widget.show-file-icons": "box-shadow: none !important",
    ".search-icon": "display: none !important;",
    ".search-label": "font-family: GeistMono Nerd Font Propo !important; font-size: 12px !important; color: #FFFF; display: block;",
    ".sidebar": "border: none !important",
    ".sidebar .title-label": "padding: 0 !important",
    ".slider": "position: absolute !important; right: 5px !important; width: 5px !important; background: #DA70D6 !important; left: auto !important;",
    ".title-label": "color: #DA70D6 !important",
    ".title .monaco-icon-label.file-icon": "margin: 0 60px",
    ".title .monaco-icon-label:after": "margin-right: 0",
    ".title-actions": "display: none !important",
    ".title.show-file-icons .label-container .monaco-icon-label.file-icon": "justify-content: center; padding: 0 !important"
  }
```
